// For all screens, buttons and texts

/*
  Need to make enum for the menu system, make sure to have defaults in place.
  struct that has all data about the menu, NO. Buttons, Array of all buttons, screen background colour, ....
  struct for buttons to have all data about them stored, background/text colour, position, size, message, being shown?, ....
  struct for text to have all data about them stored, background/text colour, position, size, message, variables, ....
*/

#ifndef  LCD_MENU_SCREENS_H_
#define LCD_MENU_SCREENS_H_

#include <stdint.h>
#include "LCD_Main.h"

// Spacing/positioning of objects
#define SPACING_5_PIXELS    5
#define SPACING_6_PIXELS    6
#define SPACING_7_PIXELS    7
#define SPACING_10_PIXELS   10
#define SPACING_15_PIXELS   15
#define SPACING_50_PIXELS   50
#define SPACING_70_PIXELS   70
#define SPACING_132_PIXELS  132
#define SCREEN_TEXT_X           70
#define SCREEN_TEXT_INITIAL_Y   70
#define SCREEN_TEXT_SPACING_Y   30

// Scalling for float variables
extern float FloatVarScaling;

/*
 *
 Back Button
 *
*/
/* LCD_Button */
#define BUTTON_BACK_X                  30
#define BUTTON_BACK_Y                  12
#define BUTTON_BACK_WIDTH              60
#define BUTTON_BACK_HEIGHT             24
#define BUTTON_BACK_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_BACK_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_BACK_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_BACK_WIDTH_SACLE        1
#define BUTTON_BACK_HEIGHT_SACLE       1

// Button Handlers
void ButtonHandler_Back_Button (void);
/*
 *
 Back Button
 *
 */

// TODO: Need to be able to hav a "pop-up" that lets user know they can't access/change a value until they unlock the device


//  Macro naming convension: [Object]_[Menu screen name]_[Specified name]_[Atribute], e.g. [BUTTON]_[MAIN_MENU]_[DATA_SCREEN]_[X]

/*
 *
 Main Menu Screen
 *
 */
/* Indexes */
// Buttons
#define BUTTON_MAIN_MENU_DATA_SELECT_ARRAY_INDEX              0
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_ARRAY_INDEX   1
#define BUTTON_MAIN_MENU_ARRAY_NUM                            2
// Texts
#define TEXT_MAIN_MENU_TITLE_SELECT_ARRAY_INDEX   0
#define TEXT_MAIN_MENU_ARRAY_NUM                  1 
// Rectangles
//#define RECTANGLE_MAIN_MENU_[Specified name here]_ARRAY_INDEX   [Value here]
#define RECTANGLE_MAIN_MENU_ARRAY_NUM  0
//#define RECTANGLE_MAIN_MENU_[Specified name here]_[Colour 1]    [Value here]
//#define RECTANGLE_MAIN_MENU_[Specified name here]_INDEX         [Value here]
// Circles
//#define CIRCLE_MAIN_MENU_[Specified name here]_ARRAY_INDEX  [Value here]
#define CIRCLE_MAIN_MENU_ARRAY_NUM  0
//#define CIRLCE_MAIN_MENU_[Specified name here]_[Colour 1]   [Value here]
//#define CIRCLE_MAIN_MENU_[Specified name here]_INDEX        [Value here]

/* LCD_Button */
// General
#define BUTTON_MAIN_MENU_BUTTON_WIDTH       120
#define BUTTON_MAIN_MENU_BUTTON_HEIGHT      40
#define BUTTON_MAIN_MENU_BUTTON_X           100
#define BUTTON_MAIN_MENU_BUTTON_INITIAL_Y   70
#define BUTTON_MAIN_MENU_BUTTON_SPACING_Y   60
// Data
#define BUTTON_MAIN_MENU_DATA_SELECT_X                  BUTTON_MAIN_MENU_BUTTON_X
#define BUTTON_MAIN_MENU_DATA_SELECT_Y                  BUTTON_MAIN_MENU_BUTTON_INITIAL_Y
#define BUTTON_MAIN_MENU_DATA_SELECT_WIDTH              BUTTON_MAIN_MENU_BUTTON_WIDTH
#define BUTTON_MAIN_MENU_DATA_SELECT_HEIGHT             BUTTON_MAIN_MENU_BUTTON_HEIGHT
#define BUTTON_MAIN_MENU_DATA_SELECT_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_MAIN_MENU_DATA_SELECT_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_MAIN_MENU_DATA_SELECT_BORDER_COLOUR      ILI9341_BLUE
#define TEXT_MAIN_MENU_DATA_SELECT_WIDTH_SACLE          2
#define TEXT_MAIN_MENU_DATA_SELECT_HEIGHT_SACLE         2
// Settings
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_X                  BUTTON_MAIN_MENU_BUTTON_X
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_Y                  BUTTON_MAIN_MENU_BUTTON_INITIAL_Y + BUTTON_MAIN_MENU_BUTTON_SPACING_Y
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_WIDTH              BUTTON_MAIN_MENU_BUTTON_WIDTH
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_HEIGHT             BUTTON_MAIN_MENU_BUTTON_HEIGHT
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_BORDER_COLOUR      ILI9341_BLUE
#define TEXT_MAIN_MENU_SETTINGS_SELECT_WIDTH_SACLE          2
#define TEXT_MAIN_MENU_SETTINGS_SELECT_HEIGHT_SACLE         2

/* LCD_Text */
// Title
#define TEXT_MAIN_MENU_TITLE_DEFAULT_FLOAT_VAL  0 // Stored value is x10 of actual
#define TEXT_MAIN_MENU_TITLE_X                  30
#define TEXT_MAIN_MENU_TITLE_Y                  5
#define TEXT_MAIN_MENU_TITLE_BACKGROUND_COLOUR  ILI9341_BLACK
#define TEXT_MAIN_MENU_TITLE_TEXT_COLOUR        ILI9341_WHITE
#define TEXT_MAIN_MENU_TITLE_DEFAULT_INT_VAL    0
#define TEXT_MAIN_MENU_TITLE_VAL_SCALING        1.0f // No value to scale
#define TEXT_MAIN_MENU_TITLE_FONT_SIZE          3
#define TEXT_MAIN_MENU_TITLE_VAR_TYPE           LCD_TEXT_VAR_TYPE_NONE

/* LCD_Rectangle */
// Rectangle 1
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_X       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_Y       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_WIDTH   [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_HEIGHT  [Value here]

/* LCD_Circle */
// Circle 1
//#define CIRCLE_MAIN_MENU_[Circle name here]_X       [Value here]
//#define CIRCLE_MAIN_MENU_[Circle name here]_Y       [Value here]
//#define CIRCLE_MAIN_MENU_[Circle name here]_RADIUS  [Value here]

// LCD_Screen_Data
#define SCREEN_MAIN_MENU_BACKGROUND_COLOUR    ILI9341_BLACK

// Global Varibles/Structs
extern LCD_Screen_Data ScreenData_MainMenu;

// Button Handlers
void ButtonHandler_MainMenu_DataScreenSelect (void);
void ButtonHandler_MainMenu_SettingsScreenSelect (void);

// Update Screen Logic Handler
//void UpdateScreenLogic_MainMenu (void);
/*
 *
 Main Menu Screen
 *
 */


/*
 *
 Data Screen
 *
 */
/* Indexes */
// Buttons
#define BUTTON_DATA_BACK_BUTTON_ARRAY_INDEX   0
#define BUTTON_DATA_ARRAY_NUM                 1
// Texts
#define TEXT_DATA_TITLE_INDEX           0
#define TEXT_DATA_TEMPERATURE_INDEX     1
#define TEXT_DATA_HUMIDITY_INDEX        2
#define TEXT_DATA_HEATER_ON_OFF_INDEX   3
#define TEXT_DATA_HEATER_MODE_INDEX     4
#define TEXT_DATA_ARRAY_NUM   5
#define TEXT_DATA_HEATER_ON_OFF_TEXT_OFF_INDEX  0
#define TEXT_DATA_HEATER_ON_OFF_TEXT_ON_INDEX   1
#define TEXT_DATA_HEATER_MODE_TEXT_AUTO_INDEX     0
#define TEXT_DATA_HEATER_MODE_TEXT_MANUAL_INDEX   1

// Rectangles
//#define RECTANGLE_DATA_[Specified name here]_ARRAY_INDEX      [Value here]
#define RECTANGLE_DATA_ARRAY_NUM  0
//#define RECTANGLE_DATA_MENU_[Specified name here]_ARRAY_[Colour 1]  [Value here]
//#define RECTANGLE_DATA_MENU_[Specified name here]_ARRAY_NUM       [Value here]
// Circles
#define CIRCLE_DATA_HEATER_ON_OFF_LED_ARRAY_INDEX   0
#define CIRCLE_DATA_ARRAY_NUM                       1
#define CIRCLE_DATA_HEATER_ON_OFF_LED_ARRAY_RED_INDEX    0
#define CIRCLE_DATA_HEATER_ON_OFF_LED_ARRAY_GREEN_INDEX  1
#define CIRCLE_DATA_HEATER_ON_OFF_LED_COLOURS_ARRAY_NUM   2

/* LCD_Button */
// [Button Name]
/*#define BUTTON__DATA_[Button Name]_X                100
#define BUTTON_DATA_[Button Name]_Y                   70
#define BUTTON_DATA_[BUTTON Name]_WIDTH               100
#define BUTTON_DATA_[BUTTON Name]_HEIGHT              40
#define BUTTON_DATA_[BUTTON Name]_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_DATA_[BUTTON Name]_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_DATA_[BUTTON Name]_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_DATA_[BUTTON Name]_WIDTH_SACLE         2
#define BUTTON_DATA_[BUTTON Name]_HEIGHT_SACLE        2 */

/* LCD_Text */
// Title
#define TEXT_DATA_TITLE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_TITLE_X                   BUTTON_BACK_X + BUTTON_BACK_WIDTH + SPACING_15_PIXELS
#define TEXT_DATA_TITLE_Y                   5
#define TEXT_DATA_TITLE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_TITLE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_TITLE_DEFAULT_INT_VAL     1
#define TEXT_DATA_TITLE_FONT_SIZE           3
#define TEXT_DATA_TITLE_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// Temperature
#define TEXT_DATA_TEMPERATURE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_TEMPERATURE_X                   SCREEN_TEXT_X
#define TEXT_DATA_TEMPERATURE_Y                   SCREEN_TEXT_INITIAL_Y
#define TEXT_DATA_TEMPERATURE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_TEMPERATURE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_TEMPERATURE_DEFAULT_INT_VAL     0
#define TEXT_DATA_TEMPERATURE_FONT_SIZE           2
#define TEXT_DATA_TEMPERATURE_VAR_TYPE            LCD_TEXT_VAR_TYPE_FLOAT
// Humidity
#define TEXT_DATA_HUMIDITY_DEFAULT_FLOAT_VAL  0 // Stored value is x10 of actual
#define TEXT_DATA_HUMIDITY_X                  SCREEN_TEXT_X
#define TEXT_DATA_HUMIDITY_Y                  SCREEN_TEXT_INITIAL_Y + SCREEN_TEXT_SPACING_Y
#define TEXT_DATA_HUMIDITY_BACKGROUND_COLOUR  ILI9341_BLACK
#define TEXT_DATA_HUMIDITY_TEXT_COLOUR        ILI9341_WHITE
#define TEXT_DATA_HUMIDITY_DEFAULT_INT_VAL    0
#define TEXT_DATA_HUMIDITY_FONT_SIZE          2
#define TEXT_DATA_HUMIDITY_VAR_TYPE           LCD_TEXT_VAR_TYPE_FLOAT
// Heater On/Off
#define TEXT_DATA_HEATER_ON_OFF_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_HEATER_ON_OFF_X                   SCREEN_TEXT_X
#define TEXT_DATA_HEATER_ON_OFF_Y                   SCREEN_TEXT_INITIAL_Y + (SCREEN_TEXT_SPACING_Y * (TEXT_DATA_HEATER_ON_OFF_INDEX - 1))
#define TEXT_DATA_HEATER_ON_OFF_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_HEATER_ON_OFF_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_HEATER_ON_OFF_DEFAULT_INT_VAL     0
#define TEXT_DATA_HEATER_ON_OFF_VAL_SCALING         1.0f // No value to scale
#define TEXT_DATA_HEATER_ON_OFF_FONT_SIZE           2
#define TEXT_DATA_HEATER_ON_OFF_VAR_TYPE            LCD_TEXT_VAR_TYPE_TEXT
// Heater Mode
#define TEXT_DATA_HEATER_MODE_DEFAULT_FLOAT_VAL   0
#define TEXT_DATA_HEATER_MODE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_HEATER_MODE_X                   SCREEN_TEXT_X
#define TEXT_DATA_HEATER_MODE_Y                   SCREEN_TEXT_INITIAL_Y + (SCREEN_TEXT_SPACING_Y * (TEXT_DATA_HEATER_MODE_INDEX - 1))
#define TEXT_DATA_HEATER_MODE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_HEATER_MODE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_HEATER_MODE_DEFAULT_INT_VAL     0
#define TEXT_DATA_HEATER_MODE_FONT_SIZE           2
#define TEXT_DATA_HEATER_MODE_VAR_TYPE            LCD_TEXT_VAR_TYPE_TEXT


/* LCD_Rectangle */
// Rectangle 1
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_X       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_Y       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_WIDTH   [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_HEIGHT  [Value here]

/* LCD_Circle */
// Heater
#define CIRCLE_DATA_HEATER_ON_OFF_LED_X       220
#define CIRCLE_DATA_HEATER_ON_OFF_LED_Y       137
#define CIRCLE_DATA_HEATER_ON_OFF_LED_RADIUS  10

// LCD_Screen_Data
#define SCREEN_DATA_BACKGROUND_COLOUR   ILI9341_BLACK

// Global Variables/Structs
extern LCD_Screen_Data ScreenData_Data;
extern float HeaterTargetTemperature;
extern uint8_t HeaterOnOffState;
extern float Temperature;
extern uint8_t HeaterMode; // 0 = Auto(Default), 1 = Manual
extern float Humidity;

// Button Handlers
//void ButtonHandler_Data_[Button Handler Name] (void);

// Update Screen Logic Handler
#define HEATER_OFF  0
#define HEATER_ON   1
#define DEFAULT_VAL_HEATER_TARGET_TEMPERATURE   30.0 // Celcius
#define HEATER_TARGET_TEMPERATURE_HYSTERESIS    1.0 // Celcius 
void UpdateScreenLogic_DataScreen (void);
/*
 *
 Data Screen
 *
 */


/*
 *
 Settings Screen
 *
 */
 /* Indexes */
// Buttons
#define BUTTON_SETTINGS_BACK_BUTTON_ARRAY_INDEX       0
#define BUTTON_SETTINGS_H_T_T_VALUE_ARRAY_INDEX       1
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_ARRAY_INDEX    2
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_ARRAY_INDEX  3
#define BUTTON_SETTINGS_HEATER_MODE_ARRAY_INDEX       4
#define BUTTON_SETTINGS_ARRAY_NUM   5
// Texts
#define TEXT_SETTINGS_TITLE_INDEX               0
#define TEXT_SETTINGS_H_T_T_PT1_INDEX           1
#define TEXT_SETTINGS_H_T_T_PT2_INDEX           2
#define TEXT_SETTINGS_H_T_T_PT3_INDEX           3
#define TEXT_SETTINGS_H_T_T_PT4_INDEX           4 // This contain the value
#define TEXT_SETTINGS_HEATER_MODE_INDEX         5
#define TEXT_SETTINGS_HEATER_MODE_VALUE_INDEX   6 // This contains the value
#define TEXT_SETTINGS_ARRAY_NUM   7
// Rectangles
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_ARRAY_INDEX  0
#define RECTANGLE_SETTINGS_ARRAY_NUM  0
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_ARRAY_GREY_INDEX   0
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_ARRAY_NUM    1
// Circles
//#define CIRCLE_SETTINGS_[Specified name here]_ARRAY_INDEX      [Value here]
#define CIRCLE_SETTINGS_ARRAY_NUM  0
//#define CIRCLE_SETTINGS_MENU_[Specified name here]_ARRAY_[Colour 1]  [Value here]
//#define CIRCLE_SETTINGS_MENU_[Specified name here]_ARRAY_NUM       [Value here]

/* LCD_Button */
// General
#define SCREEN_TEXT_SETTINGS_X  40
// Heater Temperature Target Value
#define BUTTON_SETTINGS_H_T_T_PT4_VALUE_X   SCREEN_TEXT_SETTINGS_X + SPACING_132_PIXELS
#define BUTTON_SETTINGS_H_T_T_PT4_VALUE_Y   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT2_INDEX - 1))
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH   70
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT  40
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_X       BUTTON_SETTINGS_H_T_T_PT4_VALUE_X - SPACING_10_PIXELS
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_Y       BUTTON_SETTINGS_H_T_T_PT4_VALUE_Y + SPACING_7_PIXELS
// Heater Temperature Target Value Up/down buttons
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_BUTTON_WIDTH  45
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_X             BUTTON_SETTINGS_H_T_T_PT4_VALUE_X + (BUTTON_SETTINGS_H_T_T_UP_DOWN_BUTTON_WIDTH/ 2) + SPACING_70_PIXELS
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_INITIAL_Y     80
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_SPACING_Y     30
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH         BUTTON_SETTINGS_H_T_T_UP_DOWN_BUTTON_WIDTH
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_HEIGHT        20
// Heater Mode Button
#define BUTTON_SETTINGS_HEATER_MODE_BUTTON_WIDTH  90
#define BUTTON_SETTINGS_HEATER_MODE_BUTTON_HEIGHT 30
// Heater Temperature Target Value (Invisible button, to highlight value as pressable to change)
#define BUTTON_SETTINGS_H_T_T_VALUE_X                   BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_X + (BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH / 2)
#define BUTTON_SETTINGS_H_T_T_VALUE_Y                   BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_Y
#define BUTTON_SETTINGS_H_T_T_VALUE_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_SETTINGS_H_T_T_VALUE_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_SETTINGS_H_T_T_VALUE_BACKGROUND_COLOUR   ILI9341_BLACK
#define BUTTON_SETTINGS_H_T_T_VALUE_TEXT_COLOUR         ILI9341_BLACK
#define BUTTON_SETTINGS_H_T_T_VALUE_BORDER_COLOUR       ILI9341_BLACK
#define BUTTON_SETTINGS_H_T_T_VALUE_WIDTH_SACLE         1
#define BUTTON_SETTINGS_H_T_T_VALUE_HEIGHT_SACLE        1
// Heater Temperature Target Value Up
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_X                  BUTTON_SETTINGS_H_T_T_UP_DOWN_X
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_Y                  BUTTON_SETTINGS_H_T_T_UP_DOWN_INITIAL_Y
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_WIDTH              BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_HEIGHT             BUTTON_SETTINGS_H_T_T_UP_DOWN_HEIGHT
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_WIDTH_SACLE        1
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_HEIGHT_SACLE       1
// Heater Temperature Target Value Down
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_X                  BUTTON_SETTINGS_H_T_T_UP_DOWN_X
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_Y                  BUTTON_SETTINGS_H_T_T_UP_DOWN_INITIAL_Y + BUTTON_SETTINGS_H_T_T_UP_DOWN_SPACING_Y
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_WIDTH              BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_HEIGHT             BUTTON_SETTINGS_H_T_T_UP_DOWN_HEIGHT
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_WIDTH_SACLE        1
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_HEIGHT_SACLE       1
// Heater Mode
#define BUTTON_SETTINGS_HEATER_MODE_X                   BUTTON_SETTINGS_H_T_T_PT4_VALUE_X + (BUTTON_SETTINGS_HEATER_MODE_BUTTON_WIDTH / 2) + SPACING_15_PIXELS
#define BUTTON_SETTINGS_HEATER_MODE_Y                   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT3_INDEX - 1)) + SPACING_50_PIXELS
#define BUTTON_SETTINGS_HEATER_MODE_WIDTH               BUTTON_SETTINGS_HEATER_MODE_BUTTON_WIDTH
#define BUTTON_SETTINGS_HEATER_MODE_HEIGHT              BUTTON_SETTINGS_HEATER_MODE_BUTTON_HEIGHT
#define BUTTON_SETTINGS_HEATER_MODE_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_SETTINGS_HEATER_MODE_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_SETTINGS_HEATER_MODE_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_SETTINGS_HEATER_MODE_WIDTH_SACLE         2
#define BUTTON_SETTINGS_HEATER_MODE_HEIGHT_SACLE        2

/* LCD_Text */
// Heater Target Tempearture Pt 1-3
#define TEXT_SETTINGS_H_T_T_VALUE_X           SCREEN_TEXT_SETTINGS_X
#define TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y   SCREEN_TEXT_INITIAL_Y
#define TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y   17
// Title
#define TEXT_SETTINGS_TITLE_DEFAULT_FLOAT_VAL   DEFAULT_VAL_HEATER_TARGET_TEMPERATURE // Stored value is x10 of actual
#define TEXT_SETTINGS_TITLE_X                   BUTTON_BACK_X + BUTTON_BACK_WIDTH + SPACING_5_PIXELS
#define TEXT_SETTINGS_TITLE_Y                   5
#define TEXT_SETTINGS_TITLE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_TITLE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_TITLE_DEFAULT_INT_VAL     1
#define TEXT_SETTINGS_TITLE_FONT_SIZE           3
#define TEXT_SETTINGS_TITLE_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// "Heater" Heater Target Temperature Pt 1
#define TEXT_SETTINGS_H_T_T_PT1_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT1_X                   TEXT_SETTINGS_H_T_T_VALUE_X
#define TEXT_SETTINGS_H_T_T_PT1_Y                   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT1_INDEX - 1))
#define TEXT_SETTINGS_H_T_T_PT1_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT1_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT1_DEFAULT_INT_VAL     1
#define TEXT_SETTINGS_H_T_T_PT1_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT1_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// "target" Heater Target Temperature: Pt 2
#define TEXT_SETTINGS_H_T_T_PT2_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT2_X                   SCREEN_TEXT_SETTINGS_X
#define TEXT_SETTINGS_H_T_T_PT2_Y                   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT2_INDEX - 1))
#define TEXT_SETTINGS_H_T_T_PT2_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT2_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT2_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_H_T_T_PT2_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT2_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// "temperature" Heater Target Temperature: Pt 3
#define TEXT_SETTINGS_H_T_T_PT3_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT3_X                   SCREEN_TEXT_SETTINGS_X
#define TEXT_SETTINGS_H_T_T_PT3_Y                   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT3_INDEX - 1))
#define TEXT_SETTINGS_H_T_T_PT3_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT3_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT3_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_H_T_T_PT3_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT3_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// ":" Heater Target Temperature: Pt 4
#define TEXT_SETTINGS_H_T_T_PT4_DEFAULT_FLOAT_VAL   DEFAULT_VAL_HEATER_TARGET_TEMPERATURE * 10.0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT4_X                   BUTTON_SETTINGS_H_T_T_PT4_VALUE_X
#define TEXT_SETTINGS_H_T_T_PT4_Y                   BUTTON_SETTINGS_H_T_T_PT4_VALUE_Y
#define TEXT_SETTINGS_H_T_T_PT4_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT4_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT4_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_H_T_T_PT4_VAL_SCALING         1.0f // No value to scale
#define TEXT_SETTINGS_H_T_T_PT4_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT4_VAR_TYPE            LCD_TEXT_VAR_TYPE_FLOAT
// Heater Mode
#define TEXT_SETTINGS_HEATER_MODE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_HEATER_MODE_X                   SCREEN_TEXT_SETTINGS_X
#define TEXT_SETTINGS_HEATER_MODE_Y                   BUTTON_SETTINGS_HEATER_MODE_Y - (BUTTON_SETTINGS_HEATER_MODE_BUTTON_HEIGHT / 2) + SPACING_6_PIXELS
#define TEXT_SETTINGS_HEATER_MODE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_HEATER_MODE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_HEATER_MODE_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_HEATER_MODE_VAL_SCALING         1.0f // No value to scale
#define TEXT_SETTINGS_HEATER_MODE_FONT_SIZE           2
#define TEXT_SETTINGS_HEATER_MODE_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// Heater Mode Value
#define TEXT_SETTINGS_HEATER_MODE_VALUE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_HEATER_MODE_VALUE_X                   BUTTON_SETTINGS_HEATER_MODE_X - (BUTTON_SETTINGS_HEATER_MODE_WIDTH / 3) - SPACING_5_PIXELS
#define TEXT_SETTINGS_HEATER_MODE_VALUE_Y                   BUTTON_SETTINGS_HEATER_MODE_Y - (BUTTON_SETTINGS_HEATER_MODE_BUTTON_HEIGHT / 2) + SPACING_7_PIXELS
#define TEXT_SETTINGS_HEATER_MODE_VALUE_BACKGROUND_COLOUR   ILI9341_BLUE
#define TEXT_SETTINGS_HEATER_MODE_VALUE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_HEATER_MODE_VALUE_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_HEATER_MODE_VALUE_VAL_SCALING         1.0f // No value to scale
#define TEXT_SETTINGS_HEATER_MODE_VALUE_FONT_SIZE           2
#define TEXT_SETTINGS_HEATER_MODE_VALUE_VAR_TYPE            LCD_TEXT_VAR_TYPE_TEXT

/* LCD_Rectangle */
// Heater Target Temperature Value Highlight
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_X       BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_X
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_Y       BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_Y
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_WIDTH   BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_HEIGHT  BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT

/* LCD_Circle */
// No circles to be drawn

// LCD_Screen_Data
#define SCREEN_SETTINGS_BACKGROUND_COLOUR   ILI9341_BLACK

// Global Variables/Structs
extern LCD_Screen_Data ScreenData_Settings;

// Button Handlers
#define LIMITS_LOW_H_T_T    1.0  // Celcius
#define LIMITS_HIGH_H_T_T   60.0 // Celcius
void ButtonHandler_Settings_H_T_T_Value (void);
void ButtonHandler_Settings_H_T_T_Value_Up (void);
void ButtonHandler_Settings_H_T_T_Value_Down (void);
void ButtonHandler_Settings_HeaterMode (void);

// Update Screen Logic Handler
void UpdateScreenLogic_SettingsScreen (void);
/*
 *
 Settings Screen
 *
 */

/*
 *
 Keypad Screen
 *
 */
// Button sizes
#define BUTTON_KEYPAD_NUMBERS_WIDTH   60
#define BUTTON_KEYPAD_NUMBERS_HEIGHT  60
#define BUTTON_KEYPAD_CLEAR_WIDTH     80
#define BUTTON_KEYPAD_CLEAR_HEIGHT    60
#define BUTTON_KEYPAD_DELETE_WIDTH    80
#define BUTTON_KEYPAD_DELETE_HEIGHT   60
#define BUTTON_KEYPAD_ENTER_WIDTH     80
#define BUTTON_KEYPAD_ENTER_HEIGHT    60

// Button positions
#define BUTTON_KEYPAD_NUMBERS_X  60
#define BUTTON_KEYPAD_NUMBERS_Y  60
#define BUTTON_KEYPAD_CLEAR_X    BUTTON_NUMBERS_X + (3 * (BUTTON_NUMBERS_WIDTH / 2))
#define BUTTON_KEYPAD_CLEAR_Y    BUTTON_NUMBERS_Y
#define BUTTON_KEYPAD_DELETE_X   BUTTON_NUMBERS_X + (3 * (BUTTON_NUMBERS_WIDTH / 2))
#define BUTTON_KEYPAD_DELETE_Y   BUTTON_NUMBERS_Y + (BUTTON_NUMBERS_HEIGHT / 2)
#define BUTTON_KEYPAD_ENTER_X    BUTTON_NUMBERS_X + (3 * (BUTTON_NUMBERS_WIDTH / 2))
#define BUTTON_KEYPAD_ENTER_Y    BUTTON_NUMBERS_Y + (2 * (BUTTON_NUMBERS_HEIGHT / 2))

// Text positions
#define TEXT_KEYPAD_USER_NUMBER_X  60
#define TEXT_KEYPAD_USER_NUMBER_Y  45

// Button indexes
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_0    0
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_1    1
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_2    2
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_3    3
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_4    4
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_5    5
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_6    6
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_7    7
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_8    8
#define BUTTONS_KEYPAD_ARRAY_INDEX_NUM_9    9
#define BUTTONS_KEYPAD_ARRAY_INDEX_CLEAR    10
#define BUTTONS_KEYPAD_ARRAY_INDEX_DELETE   11
#define BUTTONS_KEYPAD_ARRAY_INDEX_ENTER    12
#define BUTTONS_KEYPAD_ARRAY_INDEX_BACK     13
#define BUTTONS_KEYPAD_ARRAY_NUM            14

// Text indexes
#define TEXT_KEPAD_ARRAY_INDEX_TITLE    0
#define TEXT_KEPAD_ARRAY_INDEX_COUNTER  1
#define TEXT_KEPAD_ARRAY_NUM            2

// Global variables/Structs
extern LCD_Screen_Data ScreenData_Keypad;
extern uint16_t UserNumber;
/*
 *
 Keypad Screen
 *
 */

#endif // LCD_MENU_SCREENS_H_