// For all screens, buttons and texts

/*
  Need to make enum for the menu system, make sure to have defaults in place.
  struct that has all data about the menu, NO. Buttons, Array of all buttons, screen background colour, ....
  struct for buttons to have all data about them stored, background/text colour, position, size, message, being shown?, ....
  struct for text to have all data about them stored, background/text colour, position, size, message, variables, ....
*/

#ifndef  LCD_MENU_SCREENS_H_
#define LCD_MENU_SCREENS_H_

#include <stdint.h>
#include "LCD_Main.h"

// Screen Starting points
#define SCREEN_TEXT_X           50
#define SCREEN_TEXT_INITIAL_Y   60
#define SCREEN_TEXT_SPACING_Y   32

// Spacing/positioning of objects
#define SPACING_5_PIXELS    5
#define SPACING_6_PIXELS    6
#define SPACING_7_PIXELS    7
#define SPACING_10_PIXELS   10
#define SPACING_15_PIXELS   15
#define SPACING_50_PIXELS   50
#define SPACING_70_PIXELS   70
#define SPACING_73_PIXELS   73
#define SPACING_120_PIXELS  120
#define SPACING_132_PIXELS  132
#define SPACING_160_PIXELS  160
#define SPACING_190_PIXELS  190

// Scalling for float variables
extern float FloatVarScaling;

/*
 *
 Back Button
 *
*/
/* LCD_Button */
#define BUTTON_BACK_X                  30
#define BUTTON_BACK_Y                  12
#define BUTTON_BACK_WIDTH              60
#define BUTTON_BACK_HEIGHT             24
#define BUTTON_BACK_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_BACK_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_BACK_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_BACK_WIDTH_SACLE        1
#define BUTTON_BACK_HEIGHT_SACLE       1
#define BUTTON_BACK_DEFAULT_AVAILABLE  1

// Button Handlers
void ButtonHandler_Back_Button (void);
/*
 *
 Back Button
 *
 */

// TODO: Need to be able to hav a "pop-up" that lets user know they can't access/change a value until they unlock the device


//  Macro naming convension: [Object]_[Menu screen name]_[Specified name]_[Atribute], e.g. [BUTTON]_[MAIN_MENU]_[DATA_SCREEN]_[X]

/*
 *
 Main Menu Screen
 *
 */
/* Indexes */
// Buttons
#define BUTTON_MAIN_MENU_DATA_SELECT_ARRAY_INDEX              0
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_ARRAY_INDEX   1
#define BUTTON_MAIN_MENU_ARRAY_NUM                            2
// Texts
#define TEXT_MAIN_MENU_TITLE_SELECT_ARRAY_INDEX   0
#define TEXT_MAIN_MENU_ARRAY_NUM                  1 
// Rectangles
//#define RECTANGLE_MAIN_MENU_[Specified name here]_ARRAY_INDEX   [Value here]
#define RECTANGLE_MAIN_MENU_ARRAY_NUM  0
//#define RECTANGLE_MAIN_MENU_[Specified name here]_[Colour 1]    [Value here]
//#define RECTANGLE_MAIN_MENU_[Specified name here]_INDEX         [Value here]
// Circles
//#define CIRCLE_MAIN_MENU_[Specified name here]_ARRAY_INDEX  [Value here]
#define CIRCLE_MAIN_MENU_ARRAY_NUM  0
//#define CIRLCE_MAIN_MENU_[Specified name here]_[Colour 1]   [Value here]
//#define CIRCLE_MAIN_MENU_[Specified name here]_INDEX        [Value here]

/* LCD_Button */
// General
#define BUTTON_MAIN_MENU_BUTTON_WIDTH       120
#define BUTTON_MAIN_MENU_BUTTON_HEIGHT      40
#define BUTTON_MAIN_MENU_BUTTON_X           100
#define BUTTON_MAIN_MENU_BUTTON_INITIAL_Y   70
#define BUTTON_MAIN_MENU_BUTTON_SPACING_Y   60
// Data
#define BUTTON_MAIN_MENU_DATA_SELECT_X                  BUTTON_MAIN_MENU_BUTTON_X
#define BUTTON_MAIN_MENU_DATA_SELECT_Y                  BUTTON_MAIN_MENU_BUTTON_INITIAL_Y
#define BUTTON_MAIN_MENU_DATA_SELECT_WIDTH              BUTTON_MAIN_MENU_BUTTON_WIDTH
#define BUTTON_MAIN_MENU_DATA_SELECT_HEIGHT             BUTTON_MAIN_MENU_BUTTON_HEIGHT
#define BUTTON_MAIN_MENU_DATA_SELECT_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_MAIN_MENU_DATA_SELECT_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_MAIN_MENU_DATA_SELECT_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_MAIN_MENU_DATA_SELECT_WIDTH_SACLE        2
#define BUTTON_MAIN_MENU_DATA_SELECT_HEIGHT_SACLE       2
#define BUTTON_MAIN_MENU_DATA_SELECT_DEFAULT_AVAILABLE  1
// Settings
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_X                  BUTTON_MAIN_MENU_BUTTON_X
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_Y                  BUTTON_MAIN_MENU_BUTTON_INITIAL_Y + BUTTON_MAIN_MENU_BUTTON_SPACING_Y
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_WIDTH              BUTTON_MAIN_MENU_BUTTON_WIDTH
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_HEIGHT             BUTTON_MAIN_MENU_BUTTON_HEIGHT
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_WIDTH_SACLE        2
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_HEIGHT_SACLE       2
#define BUTTON_MAIN_MENU_SETTINGS_SELECT_DEFAULT_AVAILABLE  1

/* LCD_Text */
// Title
#define TEXT_MAIN_MENU_TITLE_DEFAULT_FLOAT_VAL  0 // Stored value is x10 of actual
#define TEXT_MAIN_MENU_TITLE_X                  30
#define TEXT_MAIN_MENU_TITLE_Y                  5
#define TEXT_MAIN_MENU_TITLE_BACKGROUND_COLOUR  ILI9341_BLACK
#define TEXT_MAIN_MENU_TITLE_TEXT_COLOUR        ILI9341_WHITE
#define TEXT_MAIN_MENU_TITLE_DEFAULT_INT_VAL    0
#define TEXT_MAIN_MENU_TITLE_VAL_SCALING        1.0f // No value to scale
#define TEXT_MAIN_MENU_TITLE_FONT_SIZE          3
#define TEXT_MAIN_MENU_TITLE_VAR_TYPE           LCD_TEXT_VAR_TYPE_NONE

/* LCD_Rectangle */
// Rectangle 1
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_X       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_Y       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_WIDTH   [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_HEIGHT  [Value here]

/* LCD_Circle */
// Circle 1
//#define CIRCLE_MAIN_MENU_[Circle name here]_X       [Value here]
//#define CIRCLE_MAIN_MENU_[Circle name here]_Y       [Value here]
//#define CIRCLE_MAIN_MENU_[Circle name here]_RADIUS  [Value here]

// LCD_Screen_Data
#define SCREEN_MAIN_MENU_BACKGROUND_COLOUR    ILI9341_BLACK

// Global Varibles/Structs
extern LCD_Screen_Data ScreenData_MainMenu;

// Button Handlers
void ButtonHandler_MainMenu_DataScreenSelect (void);
void ButtonHandler_MainMenu_SettingsScreenSelect (void);

// Update Screen Logic Handler
//void UpdateScreenLogic_MainMenu (void);
/*
 *
 Main Menu Screen
 *
 */


/*
 *
 Data Screen
 *
 */
/* Indexes */
// Buttons
#define BUTTON_DATA_BACK_BUTTON_ARRAY_INDEX     0
#define BUTTON_DATA_HEATER_ON_OFF_ARRAY_INDEX   1
#define BUTTON_DATA_HEATER_MODE_ARRAY_INDEX     2 
#define BUTTON_DATA_ARRAY_NUM   3
// Texts
#define TEXT_DATA_TITLE_INDEX               0
#define TEXT_DATA_TEMPERATURE_INDEX         1
#define TEXT_DATA_HUMIDITY_INDEX            2
#define TEXT_DATA_HEATER_ON_OFF_INDEX       3
#define TEXT_DATA_HEATER_MODE_INDEX         4
#define TEXT_DATA_HEATER_MODE_VALUE_INDEX   5
#define TEXT_DATA_ARRAY_NUM   6
#define TEXT_DATA_HEATER_ON_OFF_TEXT_OFF_INDEX  0
#define TEXT_DATA_HEATER_ON_OFF_TEXT_ON_INDEX   1
#define TEXT_DATA_HEATER_MODE_TEXT_AUTO_INDEX     0
#define TEXT_DATA_HEATER_MODE_TEXT_MANUAL_INDEX   1

// Rectangles
//#define RECTANGLE_DATA_[Specified name here]_ARRAY_INDEX      [Value here]
#define RECTANGLE_DATA_ARRAY_NUM  0
//#define RECTANGLE_DATA_MENU_[Specified name here]_ARRAY_[Colour 1]  [Value here]
//#define RECTANGLE_DATA_MENU_[Specified name here]_ARRAY_NUM       [Value here]
// Circles
#define CIRCLE_DATA_HEATER_ON_OFF_LED_ARRAY_INDEX   0
#define CIRCLE_DATA_ARRAY_NUM                       1
#define CIRCLE_DATA_HEATER_ON_OFF_LED_ARRAY_RED_INDEX    0
#define CIRCLE_DATA_HEATER_ON_OFF_LED_ARRAY_GREEN_INDEX  1
#define CIRCLE_DATA_HEATER_ON_OFF_LED_COLOURS_ARRAY_NUM   2

/* LCD_Button */
// Heater On/Off (Invisible), not available when in manual mode
#define BUTTON_DATA_HEATER_ON_OFF_X                   SCREEN_TEXT_X + SPACING_120_PIXELS
#define BUTTON_DATA_HEATER_ON_OFF_Y                   SCREEN_TEXT_INITIAL_Y + (SCREEN_TEXT_SPACING_Y * (TEXT_DATA_HEATER_ON_OFF_INDEX - 1)) + SPACING_6_PIXELS
#define BUTTON_DATA_HEATER_ON_OFF_WIDTH               110
#define BUTTON_DATA_HEATER_ON_OFF_HEIGHT              35
#define BUTTON_DATA_HEATER_ON_OFF_BACKGROUND_COLOUR   ILI9341_BLACK
#define BUTTON_DATA_HEATER_ON_OFF_TEXT_COLOUR         ILI9341_BLACK
#define BUTTON_DATA_HEATER_ON_OFF_BORDER_COLOUR       ILI9341_BLACK
#define BUTTON_DATA_HEATER_ON_OFF_WIDTH_SACLE         1
#define BUTTON_DATA_HEATER_ON_OFF_HEIGHT_SACLE        1
#define BUTTON_DATA_HEATER_ON_OFF_DEFAULT_AVAILABLE   0
// Heater Mode
#define BUTTON_DATA_HEATER_MODE_BUTTON_WIDTH               90
#define BUTTON_DATA_HEATER_MODE_BUTTON_HEIGHT              30
// Heater Mode
#define BUTTON_DATA_HEATER_MODE_X                   SCREEN_TEXT_X + SPACING_190_PIXELS
#define BUTTON_DATA_HEATER_MODE_Y                   SCREEN_TEXT_INITIAL_Y + (SCREEN_TEXT_SPACING_Y * (TEXT_DATA_HEATER_MODE_INDEX - 1)) + SPACING_7_PIXELS
#define BUTTON_DATA_HEATER_MODE_WIDTH               BUTTON_DATA_HEATER_MODE_BUTTON_WIDTH
#define BUTTON_DATA_HEATER_MODE_HEIGHT              BUTTON_DATA_HEATER_MODE_BUTTON_HEIGHT
#define BUTTON_DATA_HEATER_MODE_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_DATA_HEATER_MODE_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_DATA_HEATER_MODE_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_DATA_HEATER_MODE_WIDTH_SACLE         2
#define BUTTON_DATA_HEATER_MODE_HEIGHT_SACLE        2
#define BUTTON_DATA_HEATER_MODE_DEFAULT_AVAILABLE   1

/* LCD_Text */
// Title
#define TEXT_DATA_TITLE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_TITLE_X                   BUTTON_BACK_X + BUTTON_BACK_WIDTH + SPACING_15_PIXELS
#define TEXT_DATA_TITLE_Y                   5
#define TEXT_DATA_TITLE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_TITLE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_TITLE_DEFAULT_INT_VAL     1
#define TEXT_DATA_TITLE_FONT_SIZE           3
#define TEXT_DATA_TITLE_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// Temperature
#define TEXT_DATA_TEMPERATURE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_TEMPERATURE_X                   SCREEN_TEXT_X
#define TEXT_DATA_TEMPERATURE_Y                   SCREEN_TEXT_INITIAL_Y
#define TEXT_DATA_TEMPERATURE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_TEMPERATURE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_TEMPERATURE_DEFAULT_INT_VAL     0
#define TEXT_DATA_TEMPERATURE_FONT_SIZE           2
#define TEXT_DATA_TEMPERATURE_VAR_TYPE            LCD_TEXT_VAR_TYPE_FLOAT
// Humidity
#define TEXT_DATA_HUMIDITY_DEFAULT_FLOAT_VAL  0 // Stored value is x10 of actual
#define TEXT_DATA_HUMIDITY_X                  SCREEN_TEXT_X
#define TEXT_DATA_HUMIDITY_Y                  SCREEN_TEXT_INITIAL_Y + SCREEN_TEXT_SPACING_Y
#define TEXT_DATA_HUMIDITY_BACKGROUND_COLOUR  ILI9341_BLACK
#define TEXT_DATA_HUMIDITY_TEXT_COLOUR        ILI9341_WHITE
#define TEXT_DATA_HUMIDITY_DEFAULT_INT_VAL    0
#define TEXT_DATA_HUMIDITY_FONT_SIZE          2
#define TEXT_DATA_HUMIDITY_VAR_TYPE           LCD_TEXT_VAR_TYPE_FLOAT
// Heater On/Off
#define TEXT_DATA_HEATER_ON_OFF_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_HEATER_ON_OFF_X                   SCREEN_TEXT_X
#define TEXT_DATA_HEATER_ON_OFF_Y                   SCREEN_TEXT_INITIAL_Y + (SCREEN_TEXT_SPACING_Y * (TEXT_DATA_HEATER_ON_OFF_INDEX - 1))
#define TEXT_DATA_HEATER_ON_OFF_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_HEATER_ON_OFF_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_HEATER_ON_OFF_DEFAULT_INT_VAL     0
#define TEXT_DATA_HEATER_ON_OFF_VAL_SCALING         1.0f // No value to scale
#define TEXT_DATA_HEATER_ON_OFF_FONT_SIZE           2
#define TEXT_DATA_HEATER_ON_OFF_VAR_TYPE            LCD_TEXT_VAR_TYPE_TEXT
// Heater Mode
#define TEXT_DATA_HEATER_MODE_DEFAULT_FLOAT_VAL   0
#define TEXT_DATA_HEATER_MODE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_HEATER_MODE_X                   SCREEN_TEXT_X
#define TEXT_DATA_HEATER_MODE_Y                   SCREEN_TEXT_INITIAL_Y + (SCREEN_TEXT_SPACING_Y * (TEXT_DATA_HEATER_MODE_INDEX - 1))
#define TEXT_DATA_HEATER_MODE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_DATA_HEATER_MODE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_HEATER_MODE_DEFAULT_INT_VAL     0
#define TEXT_DATA_HEATER_MODE_FONT_SIZE           2
#define TEXT_DATA_HEATER_MODE_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// Heater Mode Value
#define TEXT_DATA_HEATER_MODE_VALUE_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_DATA_HEATER_MODE_VALUE_X                   BUTTON_DATA_HEATER_MODE_X - (BUTTON_DATA_HEATER_MODE_WIDTH / 3) - SPACING_5_PIXELS
#define TEXT_DATA_HEATER_MODE_VALUE_Y                   BUTTON_DATA_HEATER_MODE_Y - (BUTTON_DATA_HEATER_MODE_HEIGHT / 2) + SPACING_7_PIXELS
#define TEXT_DATA_HEATER_MODE_VALUE_BACKGROUND_COLOUR   ILI9341_BLUE
#define TEXT_DATA_HEATER_MODE_VALUE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_DATA_HEATER_MODE_VALUE_DEFAULT_INT_VAL     0  
#define TEXT_DATA_HEATER_MODE_VALUE_VAL_SCALING         1.0f // No value to scale
#define TEXT_DATA_HEATER_MODE_VALUE_FONT_SIZE           2
#define TEXT_DATA_HEATER_MODE_VALUE_VAR_TYPE            LCD_TEXT_VAR_TYPE_TEXT

/* LCD_Rectangle */
// Rectangle 1
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_X       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_Y       [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_WIDTH   [Value here]
//#define RECTANGLE_MAIN_MENU_[Rectangle name here]_HEIGHT  [Value here]

/* LCD_Circle */
// Heater
#define CIRCLE_DATA_HEATER_ON_OFF_LED_X       SCREEN_TEXT_X + SPACING_160_PIXELS
#define CIRCLE_DATA_HEATER_ON_OFF_LED_Y       BUTTON_DATA_HEATER_ON_OFF_Y
#define CIRCLE_DATA_HEATER_ON_OFF_LED_RADIUS  10

// LCD_Screen_Data
#define SCREEN_DATA_BACKGROUND_COLOUR   ILI9341_BLACK

// Global Variables/Structs
extern LCD_Screen_Data ScreenData_Data;
extern float HeaterTargetTemperature;
extern uint8_t HeaterOnOffState;
extern float Temperature;
extern uint8_t HeaterMode; // 0 = Auto(Default), 1 = Manual
extern float Humidity;

// Button Handlers
void ButtonHandler_Data_HeaterOnOff(void);
void ButtonHandler_Data_HeaterMode(void);

// Update Screen Logic Handler
#define HEATER_OFF  0
#define HEATER_ON   1
#define DEFAULT_VAL_HEATER_TARGET_TEMPERATURE   30.0 // Celcius
#define HEATER_TARGET_TEMPERATURE_HYSTERESIS    1.0 // Celcius 
void UpdateScreenLogic_DataScreen(void);
/*
 *
 Data Screen
 *
 */


/*
 *
 Settings Screen
 *
 */
 /* Indexes */
// Buttons
#define BUTTON_SETTINGS_BACK_BUTTON_ARRAY_INDEX       0
#define BUTTON_SETTINGS_H_T_T_VALUE_ARRAY_INDEX       1
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_ARRAY_INDEX    2
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_ARRAY_INDEX  3
#define BUTTON_SETTINGS_ARRAY_NUM   4
// Texts
#define TEXT_SETTINGS_TITLE_INDEX               0
#define TEXT_SETTINGS_H_T_T_PT1_INDEX           1
#define TEXT_SETTINGS_H_T_T_PT2_INDEX           2
#define TEXT_SETTINGS_H_T_T_PT3_INDEX           3
#define TEXT_SETTINGS_H_T_T_PT4_INDEX           4 // This contain the value
#define TEXT_SETTINGS_HEATER_MODE_INDEX         5
#define TEXT_SETTINGS_ARRAY_NUM   6
// Rectangles
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_ARRAY_INDEX  0
#define RECTANGLE_SETTINGS_ARRAY_NUM  0
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_ARRAY_GREY_INDEX   0
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_ARRAY_NUM    1
// Circles
//#define CIRCLE_SETTINGS_[Specified name here]_ARRAY_INDEX      [Value here]
#define CIRCLE_SETTINGS_ARRAY_NUM  0
//#define CIRCLE_SETTINGS_MENU_[Specified name here]_ARRAY_[Colour 1]  [Value here]
//#define CIRCLE_SETTINGS_MENU_[Specified name here]_ARRAY_NUM       [Value here]

/* LCD_Button */
// General
#define SCREEN_TEXT_SETTINGS_X  40
// Heater Temperature Target Value
#define BUTTON_SETTINGS_H_T_T_PT4_VALUE_X   SCREEN_TEXT_SETTINGS_X + SPACING_132_PIXELS
#define BUTTON_SETTINGS_H_T_T_PT4_VALUE_Y   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT2_INDEX - 1))
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH   70
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT  40
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_X       BUTTON_SETTINGS_H_T_T_PT4_VALUE_X - SPACING_10_PIXELS
#define BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_Y       BUTTON_SETTINGS_H_T_T_PT4_VALUE_Y + SPACING_7_PIXELS
// Heater Temperature Target Value Up/down buttons
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH       45
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_HEIGHT      20
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_SPACING_Y   30
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_X           BUTTON_SETTINGS_H_T_T_PT4_VALUE_X + (BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH/ 2) + SPACING_73_PIXELS
#define BUTTON_SETTINGS_H_T_T_UP_DOWN_INITIAL_Y   BUTTON_SETTINGS_H_T_T_PT4_VALUE_Y - (BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH / 2) + (BUTTON_SETTINGS_H_T_T_UP_DOWN_SPACING_Y / 2)
// Heater Temperature Target Value (Invisible button)
#define BUTTON_SETTINGS_H_T_T_VALUE_X                   BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_X + (BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH / 2)
#define BUTTON_SETTINGS_H_T_T_VALUE_Y                   BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_Y
#define BUTTON_SETTINGS_H_T_T_VALUE_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_SETTINGS_H_T_T_VALUE_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_SETTINGS_H_T_T_VALUE_BACKGROUND_COLOUR   ILI9341_BLACK
#define BUTTON_SETTINGS_H_T_T_VALUE_TEXT_COLOUR         ILI9341_BLACK
#define BUTTON_SETTINGS_H_T_T_VALUE_BORDER_COLOUR       ILI9341_BLACK
#define BUTTON_SETTINGS_H_T_T_VALUE_WIDTH_SACLE         1
#define BUTTON_SETTINGS_H_T_T_VALUE_HEIGHT_SACLE        1
#define BUTTON_SETTINGS_H_T_T_VALUE_DEFAULT_AVAILABLE   1
// Heater Temperature Target Value Up
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_X                  BUTTON_SETTINGS_H_T_T_UP_DOWN_X
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_Y                  BUTTON_SETTINGS_H_T_T_UP_DOWN_INITIAL_Y
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_WIDTH              BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_HEIGHT             BUTTON_SETTINGS_H_T_T_UP_DOWN_HEIGHT
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_WIDTH_SACLE        1
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_HEIGHT_SACLE       1
#define BUTTON_SETTINGS_H_T_T_VALUE_UP_DEFAULT_AVAILABLE  1
// Heater Temperature Target Value Down
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_X                  BUTTON_SETTINGS_H_T_T_UP_DOWN_X
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_Y                  BUTTON_SETTINGS_H_T_T_UP_DOWN_INITIAL_Y + BUTTON_SETTINGS_H_T_T_UP_DOWN_SPACING_Y
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_WIDTH              BUTTON_SETTINGS_H_T_T_UP_DOWN_WIDTH
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_HEIGHT             BUTTON_SETTINGS_H_T_T_UP_DOWN_HEIGHT
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_WIDTH_SACLE        1
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_HEIGHT_SACLE       1
#define BUTTON_SETTINGS_H_T_T_VALUE_DOWN_DEFAULT_AVAILABLE  1

/* LCD_Text */
// Heater Target Tempearture Pt 1-3
#define TEXT_SETTINGS_H_T_T_VALUE_X           SCREEN_TEXT_SETTINGS_X
#define TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y   SCREEN_TEXT_INITIAL_Y
#define TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y   17
// Title
#define TEXT_SETTINGS_TITLE_DEFAULT_FLOAT_VAL   DEFAULT_VAL_HEATER_TARGET_TEMPERATURE // Stored value is x10 of actual
#define TEXT_SETTINGS_TITLE_X                   BUTTON_BACK_X + BUTTON_BACK_WIDTH + SPACING_5_PIXELS
#define TEXT_SETTINGS_TITLE_Y                   5
#define TEXT_SETTINGS_TITLE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_TITLE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_TITLE_DEFAULT_INT_VAL     1
#define TEXT_SETTINGS_TITLE_FONT_SIZE           3
#define TEXT_SETTINGS_TITLE_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// "Heater" Heater Target Temperature Pt 1
#define TEXT_SETTINGS_H_T_T_PT1_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT1_X                   TEXT_SETTINGS_H_T_T_VALUE_X
#define TEXT_SETTINGS_H_T_T_PT1_Y                   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT1_INDEX - 1))
#define TEXT_SETTINGS_H_T_T_PT1_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT1_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT1_DEFAULT_INT_VAL     1
#define TEXT_SETTINGS_H_T_T_PT1_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT1_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// "target" Heater Target Temperature: Pt 2
#define TEXT_SETTINGS_H_T_T_PT2_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT2_X                   SCREEN_TEXT_SETTINGS_X
#define TEXT_SETTINGS_H_T_T_PT2_Y                   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT2_INDEX - 1))
#define TEXT_SETTINGS_H_T_T_PT2_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT2_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT2_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_H_T_T_PT2_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT2_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// "temperature" Heater Target Temperature: Pt 3
#define TEXT_SETTINGS_H_T_T_PT3_DEFAULT_FLOAT_VAL   0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT3_X                   SCREEN_TEXT_SETTINGS_X
#define TEXT_SETTINGS_H_T_T_PT3_Y                   TEXT_SETTINGS_H_T_T_VALUE_INITIAL_Y + (TEXT_SETTINGS_H_T_T_VALUE_SPACING_Y * (TEXT_SETTINGS_H_T_T_PT3_INDEX - 1))
#define TEXT_SETTINGS_H_T_T_PT3_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT3_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT3_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_H_T_T_PT3_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT3_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// ":" Heater Target Temperature: Pt 4
#define TEXT_SETTINGS_H_T_T_PT4_DEFAULT_FLOAT_VAL   DEFAULT_VAL_HEATER_TARGET_TEMPERATURE * 10.0 // Stored value is x10 of actual
#define TEXT_SETTINGS_H_T_T_PT4_X                   BUTTON_SETTINGS_H_T_T_PT4_VALUE_X
#define TEXT_SETTINGS_H_T_T_PT4_Y                   BUTTON_SETTINGS_H_T_T_PT4_VALUE_Y
#define TEXT_SETTINGS_H_T_T_PT4_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_SETTINGS_H_T_T_PT4_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_SETTINGS_H_T_T_PT4_DEFAULT_INT_VAL     0
#define TEXT_SETTINGS_H_T_T_PT4_VAL_SCALING         1.0f // No value to scale
#define TEXT_SETTINGS_H_T_T_PT4_FONT_SIZE           2
#define TEXT_SETTINGS_H_T_T_PT4_VAR_TYPE            LCD_TEXT_VAR_TYPE_FLOAT

/* LCD_Rectangle */
// Heater Target Temperature Value Highlight
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_X       BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_X
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_Y       BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_Y
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_WIDTH   BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
//#define RECTANGLE_SETTINGS_H_T_T_VALUE_HEIGHT  BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT

/* LCD_Circle */
// No circles to be drawn

// LCD_Screen_Data
#define SCREEN_SETTINGS_BACKGROUND_COLOUR   ILI9341_BLACK

// Global Variables/Structs
extern LCD_Screen_Data ScreenData_Settings;

// Button Handlers
#define LIMITS_LOW_H_T_T    1.0  // Celcius
#define LIMITS_HIGH_H_T_T   60.0 // Celcius
void ButtonHandler_Settings_H_T_T_Value(void);
void ButtonHandler_Settings_H_T_T_Value_Up(void);
void ButtonHandler_Settings_H_T_T_Value_Down(void);
void ButtonHandler_Settings_HeaterMode(void);

// Update Screen Logic Handler
void UpdateScreenLogic_SettingsScreen (void);
/*
 *
 Settings Screen
 *
 */

/*
 *
 Keypad Screen
 *
 */
 /* Indexes */
// Buttons
#define BUTTON_KEYPAD_CANCEL_BUTTON_ARRAY_INDEX   0
#define BUTTON_KEYPAD_NUM_0_ARRAY_INDEX           1
#define BUTTON_KEYPAD_NUM_1_ARRAY_INDEX           2
#define BUTTON_KEYPAD_NUM_2_ARRAY_INDEX           3
#define BUTTON_KEYPAD_NUM_3_ARRAY_INDEX           4
#define BUTTON_KEYPAD_NUM_4_ARRAY_INDEX           5
#define BUTTON_KEYPAD_NUM_5_ARRAY_INDEX           6
#define BUTTON_KEYPAD_NUM_6_ARRAY_INDEX           7
#define BUTTON_KEYPAD_NUM_7_ARRAY_INDEX           8
#define BUTTON_KEYPAD_NUM_8_ARRAY_INDEX           9
#define BUTTON_KEYPAD_NUM_9_ARRAY_INDEX           10
#define BUTTON_KEYPAD_DELETE_ARRAY_INDEX          11
#define BUTTON_KEYPAD_ENTER_ARRAY_INDEX           12
#define BUTTON_KEYPAD_ARRAY_NUM   13
// Texts
#define TEXT_KEYPAD_TITLE_INDEX     0
#define TEXT_KEYPAD_USER_NUM_INDEX  1
#define TEXT_KEYPAD_ARRAY_NUM   2

// Rectangles
//#define RECTANGLE_KEYPAD_[Rectangle name]_ARRAY_INDEX  [Value here]
#define RECTANGLE_KEYPAD_ARRAY_NUM  0
//#define RECTANGLE_KEYPAD_[Rectangle name]_ARRAY_[Colour]_INDEX  [Value here]
//#define RECTANGLE_KEYPAD_[Rectangle name]_ARRAY_[Colour]_NUM    [Value here]
// Circles
//#define CIRCLE_KEYPAD_[Circle name]_ARRAY_INDEX  [Value here]
#define CIRCLE_KEYPAD_ARRAY_NUM  0
//#define CIRCLE_KEYPAD_[Circle name]_ARRAY_[Colour]_INDEX  [Value here]
//#define CIRCLE_KEYPAD_[Circle name]_ARRAY_[Colour]_NUM    [Value here]e]

/* LCD_Button */
// General
#define KEYPAD_BUTTON_WIDTH   30
#define KEYPAD_BUTTON_HEIGHT  30
#define KEYPAD_BUTTON_COLUMN_SPACING   KEYPAD_BUTTON_HEIGHT + SPACING_10_PIXELS
#define KEYPAD_BUTTON_COLUMN_1_X       30
#define KEYPAD_BUTTON_COLUMN_2_X       KEYPAD_BUTTON_COLUMN_1_X + (2 * KEYPAD_BUTTON_COLUMN_SPACING)
#define KEYPAD_BUTTON_COLUMN_3_X       KEYPAD_BUTTON_COLUMN_1_X + (2 * KEYPAD_BUTTON_COLUMN_SPACING)
#define KEYPAD_BUTTON_ROW_SPACING  KEYPAD_BUTTON_WIDTH + SPACING_10_PIXELS
#define KEYPAD_BUTTON_ROW_1_Y      60
#define KEYPAD_BUTTON_ROW_2_Y      KEYPAD_BUTTON_ROW_1_Y + KEYPAD_BUTTON_ROW_SPACING
#define KEYPAD_BUTTON_ROW_3_Y      KEYPAD_BUTTON_ROW_1_Y + (2 * KEYPAD_BUTTON_ROW_SPACING)
#define KEYPAD_BUTTON_ROW_4_Y      KEYPAD_BUTTON_ROW_1_Y + (3 * KEYPAD_BUTTON_ROW_SPACING)

// Cancel
#define BUTTON_KEYPAD_CANCEL_X                  30
#define BUTTON_KEYPAD_CANCEL_Y                  12
#define BUTTON_KEYPAD_CANCEL_WIDTH              70
#define BUTTON_KEYPAD_CANCEL_HEIGHT             24
#define BUTTON_KEYPAD_CANCEL_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_KEYPAD_CANCEL_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_KEYPAD_CANCEL_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_KEYPAD_CANCEL_WIDTH_SACLE        1
#define BUTTON_KEYPAD_CANCEL_HEIGHT_SACLE       1
#define BUTTON_KEYPAD_CANCEL_DEFAULT_AVAILABLE  1
// Num 0
#define BUTTON_KEYPAD_NUM_0_X                   KEYPAD_BUTTON_COLUMN_2_X
#define BUTTON_KEYPAD_NUM_0_Y                   KEYPAD_BUTTON_ROW_4_Y
#define BUTTON_KEYPAD_NUM_0_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_0_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_0_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_0_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_0_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_0_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_0_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_0_DEFAULT_AVAILABLE   1
// Num 1
#define BUTTON_KEYPAD_NUM_1_X                   KEYPAD_BUTTON_COLUMN_1_X
#define BUTTON_KEYPAD_NUM_1_Y                   KEYPAD_BUTTON_ROW_1_Y
#define BUTTON_KEYPAD_NUM_1_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_1_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_1_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_1_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_1_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_1_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_1_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_1_DEFAULT_AVAILABLE   1
// Num 2
#define BUTTON_KEYPAD_NUM_2_X                   KEYPAD_BUTTON_COLUMN_2_X
#define BUTTON_KEYPAD_NUM_2_Y                   KEYPAD_BUTTON_ROW_1_Y
#define BUTTON_KEYPAD_NUM_2_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_2_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_2_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_2_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_2_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_2_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_2_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_2_DEFAULT_AVAILABLE   1
// Num 3
#define BUTTON_KEYPAD_NUM_3_X                   KEYPAD_BUTTON_COLUMN_3_X
#define BUTTON_KEYPAD_NUM_3_Y                   KEYPAD_BUTTON_ROW_1_Y
#define BUTTON_KEYPAD_NUM_3_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_3_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_3_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_3_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_3_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_3_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_3_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_3_DEFAULT_AVAILABLE   1
// Num 4
#define BUTTON_KEYPAD_NUM_4_X                   KEYPAD_BUTTON_COLUMN_1_X
#define BUTTON_KEYPAD_NUM_4_Y                   KEYPAD_BUTTON_ROW_2_Y
#define BUTTON_KEYPAD_NUM_4_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_4_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_4_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_4_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_4_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_4_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_4_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_4_DEFAULT_AVAILABLE   1
// Num 5
#define BUTTON_KEYPAD_NUM_5_X                   KEYPAD_BUTTON_COLUMN_2_X
#define BUTTON_KEYPAD_NUM_5_Y                   KEYPAD_BUTTON_ROW_2_Y
#define BUTTON_KEYPAD_NUM_5_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_5_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_5_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_5_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_5_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_5_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_5_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_5_DEFAULT_AVAILABLE   1
// Num 6
#define BUTTON_KEYPAD_NUM_6_X                   KEYPAD_BUTTON_COLUMN_3_X
#define BUTTON_KEYPAD_NUM_6_Y                   KEYPAD_BUTTON_ROW_2_Y
#define BUTTON_KEYPAD_NUM_6_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_6_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_6_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_6_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_6_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_6_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_6_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_6_DEFAULT_AVAILABLE   1
// Num 7
#define BUTTON_KEYPAD_NUM_7_X                   KEYPAD_BUTTON_COLUMN_1_X
#define BUTTON_KEYPAD_NUM_7_Y                   KEYPAD_BUTTON_ROW_3_Y
#define BUTTON_KEYPAD_NUM_7_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_7_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_7_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_7_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_7_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_7_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_7_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_7_DEFAULT_AVAILABLE   1
// Num 8
#define BUTTON_KEYPAD_NUM_8_X                   KEYPAD_BUTTON_COLUMN_2_X
#define BUTTON_KEYPAD_NUM_8_Y                   KEYPAD_BUTTON_ROW_3_Y
#define BUTTON_KEYPAD_NUM_8_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_8_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_8_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_8_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_8_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_8_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_8_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_8_DEFAULT_AVAILABLE   1
// Num 9
#define BUTTON_KEYPAD_NUM_9_X                   KEYPAD_BUTTON_COLUMN_3_X
#define BUTTON_KEYPAD_NUM_9_Y                   KEYPAD_BUTTON_ROW_3_Y
#define BUTTON_KEYPAD_NUM_9_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_NUM_9_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_NUM_9_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_9_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_NUM_9_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_NUM_9_WIDTH_SACLE         1
#define BUTTON_KEYPAD_NUM_9_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_NUM_9_DEFAULT_AVAILABLE   1
// Delete
#define BUTTON_KEYPAD_DELETE_X                  KEYPAD_BUTTON_COLUMN_1_X
#define BUTTON_KEYPAD_DELETE_Y                  KEYPAD_BUTTON_ROW_4_Y
#define BUTTON_KEYPAD_DELETE_WIDTH              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_DELETE_HEIGHT             BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_DELETE_BACKGROUND_COLOUR  ILI9341_BLUE
#define BUTTON_KEYPAD_DELETE_TEXT_COLOUR        ILI9341_WHITE
#define BUTTON_KEYPAD_DELETE_BORDER_COLOUR      ILI9341_BLUE
#define BUTTON_KEYPAD_DELETE_WIDTH_SACLE        1
#define BUTTON_KEYPAD_DELETE_HEIGHT_SACLE       1
#define BUTTON_KEYPAD_DELETE_DEFAULT_AVAILABLE  1
// Enter
#define BUTTON_KEYPAD_ENTER_X                   KEYPAD_BUTTON_COLUMN_3_X
#define BUTTON_KEYPAD_ENTER_Y                   KEYPAD_BUTTON_ROW_4_Y
#define BUTTON_KEYPAD_ENTER_WIDTH               BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_WIDTH
#define BUTTON_KEYPAD_ENTER_HEIGHT              BUTTON_SETTINGS_H_T_T_VALUE_BUTTON_HEIGHT
#define BUTTON_KEYPAD_ENTER_BACKGROUND_COLOUR   ILI9341_BLUE
#define BUTTON_KEYPAD_ENTER_TEXT_COLOUR         ILI9341_WHITE
#define BUTTON_KEYPAD_ENTER_BORDER_COLOUR       ILI9341_BLUE
#define BUTTON_KEYPAD_ENTER_WIDTH_SACLE         1
#define BUTTON_KEYPAD_ENTER_HEIGHT_SACLE        1
#define BUTTON_KEYPAD_ENTER_DEFAULT_AVAILABLE   1

/* LCD_Text */
// Title
#define TEXT_KEYPAD_TITLE_DEFAULT_FLOAT_VAL   DEFAULT_VAL_HEATER_TARGET_TEMPERATURE // Stored value is x10 of actual
#define TEXT_KEYPAD_TITLE_X                   BUTTON_KEYPAD_CANCEL_X + (BUTTON_KEYPAD_CANCEL_WIDTH / 2) + SPACING_5_PIXELS
#define TEXT_KEYPAD_TITLE_Y                   5
#define TEXT_KEYPAD_TITLE_BACKGROUND_COLOUR   ILI9341_BLACK
#define TEXT_KEYPAD_TITLE_TEXT_COLOUR         ILI9341_WHITE
#define TEXT_KEYPAD_TITLE_DEFAULT_INT_VAL     0
#define TEXT_KEYPAD_TITLE_FONT_SIZE           3
#define TEXT_KEYPAD_TITLE_VAR_TYPE            LCD_TEXT_VAR_TYPE_NONE
// User value
#define TEXT_KEYPAD_USER_VALUE_DEFAULT_FLOAT_VAL  0 // Stored value is x10 of actual
#define TEXT_KEYPAD_USER_VALUE_X                  15
#define TEXT_KEYPAD_USER_VALUE_Y                  50
#define TEXT_KEYPAD_USER_VALUE_BACKGROUND_COLOUR  ILI9341_BLACK
#define TEXT_KEYPAD_USER_VALUE_TEXT_COLOUR        ILI9341_WHITE
#define TEXT_KEYPAD_USER_VALUE_DEFAULT_INT_VAL    0
#define TEXT_KEYPAD_USER_VALUE_FONT_SIZE          2
#define TEXT_KEYPAD_USER_VALUE_VAR_TYPE           LCD_TEXT_VAR_TYPE_INT

/* LCD_Rectangle */
// No rectangles to be drawn

/* LCD_Circle */
// No circles to be drawn

// LCD_Screen_Data
#define SCREEN_KEYPAD_BACKGROUND_COLOUR   ILI9341_BLACK

// Global Variables/Structs
extern LCD_Screen_Data ScreenData_Keypad;
extern uint8_t EnteredKeypadNumber;

// Button Handlers
void ButtonHandler_Keypad_Cancel(void);
void ButtonHandler_Keypad_Num_0(void);
void ButtonHandler_Keypad_Num_1(void);
void ButtonHandler_Keypad_Num_2(void);
void ButtonHandler_Keypad_Num_3(void);
void ButtonHandler_Keypad_Num_4(void);
void ButtonHandler_Keypad_Num_5(void);
void ButtonHandler_Keypad_Num_6(void);
void ButtonHandler_Keypad_Num_7(void);
void ButtonHandler_Keypad_Num_8(void);
void ButtonHandler_Keypad_Num_9(void);
void ButtonHandler_Keypad_Delete(void);
void ButtonHandler_Keypad_Enter(void);

// Update Screen Logic Handler
void UpdateScreenLogic_KeypadScreen(void);
/*
 *
 Keypad Screen
 *
 */

#endif // LCD_MENU_SCREENS_H_